### ISSUE TITLE
GoogleImageSearcher - Ready for review

### ISSUE THREAD

**Issue by AshwiniThonteswaramurthy** [AshwiniThonteswaramurthy/GoogleImageSearcher#1]
GoogleImageSearcher app is almost complete. Please review. /cc @codepathreview @codepath

Also, I would like to know if there is any way of adding a share like pinterest. I tried satellite menu and arc menu which displays a button (pinterest doesnt). I also tried to set button to be invisible and cant seem to fix the location of where the arc's appear.

Any advise would be greatly appreciated.

Thanks, 
Ashwini

**Comment by codepathreview** [comment]
:+1: Excellent work overall!!! A few notes after checking out the code:
- Great work on packaging the code correctly
- Good job using Parcelable instead of Serializable ([benefits](http://stackoverflow.com/a/5551155))
- Good job using the ConnectivityManager to check for network availability and notifying user about failure
- Great job implementing SettingsDialog for filters.
- Good job using StaggeredGridView and TouchImageView for enhancing UI/UX
- Good to see you added Search using the action bar and correctly implemented sharing 
- Good to see JSON deserializing logic in the model object. (Consider adding null checks)

Also, here's a more detailed [Project 2 Feedback Guide here](https://gist.github.com/nesquena/44091e4727b154d04269) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](https://gist.github.com/nesquena/44091e4727b154d04269) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
